[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "scoreoperator"
version = "0.2.0"
description = "A package for paper: Infinite-dimensional Diffusion Bridge Simulation via Operator Learning"
authors = [{name = "Gefan Yang", email = "gy@di.ku.dk"}]
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "scipy",
    "flax",
    "optax",
    "matplotlib",
    "ml_collections",
    "pytest",
]

[project.optional-dependencies]
cpu = ["jax[cpu]"]
gpu = ["jax[cuda12]"]

[project.urls]
"Homepage" = "https://github.com/bookdiver/scoreoperator"

[tool.setuptools.packages.find]
where = ["scoreoperator"]

[tool.setuptools.package-data]
"*" = ["*.txt", "*.rst"]