quadratic_brownian:
  data:
    type: quadratic
    start_point:
      a: 1.0
      c: 0.0
    end_point:
      a: -1.0
      c: 0.0
  diffusion_bridge:
    sde_name: brownian
    sde_kwargs: 
      T: 1.0
      sigma: 0.1
      W_shape: [8, 1]
    dt: 2.0e-2
  neural_op:
    do_dim: 1
    in_co_dim: 1
    out_co_dim: 1
    lifting_dim: 16
    co_dims_fmults: [1, 2, 4]
    grid_scaling_fmults: [1.0, 0.5, 0.5]
    n_modes_per_layer: [[6, ], [4, ], [2, ]]
    act: gelu
    norm: batch
  training:
    dir: ../ckpts/quadratic_brownian/
    seed: 42
    n_train_pts: [8, ]
    lr: 5.0e-4
    batch_sz: 16
    opt_name: adam
    clip_grads: True
    warmup_steps: 250
    train_n_iters: 5000
    checkpoint_freq: 1000

ellipse_brownian:
  data:
    type: ellipse
    start_point:
      a: 1.25
      b: 0.85
    end_point:
      a: 1.5
      b: 0.5 
  diffusion_bridge:
    sde_name: brownian
    sde_kwargs:
      T: 1.0
      sigma: 0.1
      W_shape: [64, 2]
    dt: 1.0e-2
  neural_op:
    do_dim: 1
    in_co_dim: 2
    out_co_dim: 2
    lifting_dim: 16
    co_dims_fmults: [1, 2, 4]
    grid_scaling_fmults: [1.0, 1.0, 0.5]
    n_modes_per_layer: [[32, ], [24, ], [16, ]]
    act: gelu
    norm: batch
  training:
    dir: ../ckpts/ellipse_brownian/
    seed: 42
    n_train_pts: [64, ]
    lr: 2.0e-4
    batch_sz: 16
    opt_name: adam
    clip_grads: False
    warmup_steps: 500
    train_n_iters: 10000
    checkpoint_freq: 10000

ellipse_lagrangian:
  diffusion_bridge:
    sde_name: lagrangian
    sde_kwargs:
      T: 1.0
      sigma: 0.1
      kappa: 0.2
    dt: 1.0e-2
  neural_op:
    in_co_dim: 2
    out_co_dim: 2
    lifting_dim: 16
    co_dims_fmults: [1, 2, 4, 4]
    n_modes_per_layer: [8, 6, 4, 4]
    act: gelu
    norm: batch
  training:
    dir: ../ckpts/ellipse_lagrangian/
    seed: 42
    n_train_pts: 16
    lr: 2.0e-4
    batch_sz: 16
    opt_name: adam
    warmup_steps: 500
    train_n_iters: 10000
    checkpoint_freq: 1000

ellipse_eulerian:
  data:
    type: ellipse
    start_point:
      a: 1.25
      b: 0.85
    end_point:
      a: 1.5
      b: 0.5  
  diffusion_bridge:
    sde_name: eulerian
    sde_kwargs:
      T: 1.0
      sigma: 0.05
      kappa: 0.1
      W_shape: (64, 64, 2)
      W_range: ((-1.75, 1.75), (-1.25, 1.25))
    dt: 1.0e-2
  neural_op:
    do_dim: 1
    in_co_dim: 2
    out_co_dim: 2
    lifting_dim: 32
    co_dims_fmults: (1, 2, 4)
    n_modes_per_layer: ((12, ), (8, ), (4, ))
    act: gelu
    norm: batch
  training:
    dir: ../ckpts/ellipse_eulerian/
    seed: 42
    n_train_pts: (16, )
    lr: 2.0e-4
    batch_sz: 16
    opt_name: adam
    warmup_steps: 500
    train_n_iters: 10000
    checkpoint_freq: 1000

ellipsoid_brownian:
  data:
    type: ellipsoid
    start_point:
      a: 0.5
      b: 0.5
      c: 0.5
    end_point:
      a: 0.8
      b: 0.8
      c: 0.8
  diffusion_bridge:
    sde_name: brownian
    sde_kwargs:
      T: 1.0
      sigma: 0.2
      W_shape: [16, 16, 3]
    dt: 1.0e-2
  neural_op:
    do_dim: 2
    in_co_dim: 3
    out_co_dim: 3
    lifting_dim: 32
    co_dims_fmults: [1, 2, 4]
    grid_scaling_fmults: [1.0, 1.0, 0.5]
    n_modes_per_layer: [[12, 12], [8, 8], [4, 4]]
    act: gelu
    norm: batch
  training:
    dir: ../ckpts/ellipsoid_brownian/
    seed: 42
    n_train_pts: [16, 16]
    lr: 2.0e-4
    batch_sz: 16
    opt_name: adam
    clip_grads: False
    warmup_steps: 500
    train_n_iters: 10000
    checkpoint_freq: 1000

# butterflies_brownian:
# TODO: to be finished

butterflies_lagrangian:
  diffusion_bridge:
    sde_name: lagrangian
    sde_kwargs:
      T: 1.0
      sigma: 0.03
      kappa: 0.08
    dt: 1.0e-2
  neural_op:
    in_co_dim: 2
    out_co_dim: 2
    lifting_dim: 16
    co_dims_fmults: [1, 2, 4, 4]
    n_modes_per_layer: [16, 8, 6, 6]
    act: gelu
    norm: batch
  training:
    dir: ./pretrained/butterflies_lagrangian/
    seed: 42
    n_train_pts: 32
    lr: 2.0e-4
    batch_sz: 16
    opt_name: adam
    warmup_steps: 1000
    train_n_iters: 20000
    checkpoint_freq: 2000

butterflies_eulerian:
  diffusion_bridge:
    sde_name: eulerian
    sde_kwargs:
      T: 1.0
      sigma: 0.04
      kappa: 0.02
      W_shape: (64, 64)
      W_range: ((-0.5, 1.5), (-0.5, 1.5))
    dt: 1.0e-2
  neural_op:
    in_co_dim: 2
    out_co_dim: 2
    lifting_dim: 16
    co_dims_fmults: [1, 2, 4, 4]
    n_modes_per_layer: [16, 8, 6, 6]
    act: gelu
    norm: batch
  training:
    dir: ./pretrained/butterflies_eulerian
    seed: 42
    n_train_pts: 32
    lr: 2.0e-4
    batch_sz: 16
    opt_name: adam
    warmup_steps: 1000
    train_n_iters: 20000
    checkpoint_freq: 2000

# quadratic_brownian:
#   sde:
#     name: brownian
#     sigma: 0.1
#   diffusion:
#     matching_obj: g2score
#     dt: 2.0e-2
#   model:
#     name: uno
#     out_co_dim: 1
#     lifting_dim: 16
#     co_dims_fmults: [1, 2, 4]
#     n_modes_per_layer: [6, 4, 2]
#     act: gelu
#     norm: batch
#   training:
#     seed: 42
#     n_train_pts: 8
#     n_test_pts: 128
#     learning_rate: 1.0e-3
#     batch_size: 16
#     optimizer_name: adam
#     warmup_steps: 500
#     train_num_epochs: 100
#     train_num_steps_per_epoch: 100

# quadratic_ou:
#   sde:
#     name: ou
#     sigma: 0.5
#     theta: 0.1
#   diffusion:
#     matching_obj: score
#     dt: 2.0e-2
#   model:
#     out_co_dim: 1
#     lifting_dim: 16
#     co_dims_fmults: [1, 2, 4]
#     n_modes_per_layer: [6, 4, 2]
#     act: gelu
#     norm: batch
#   training:
#     seed: 42
#     n_train_pts: 8
#     n_test_pts: 128
#     learning_rate: 1.0e-3
#     batch_size: 16
#     optimizer_name: adam
#     warmup_steps: 500
#     train_num_epochs: 100
#     train_num_steps_per_epoch: 100